project:
  type: website
output-dir: docs

website:
  title: "Bradford Johnson"
  navbar:
    right: 
      - text: "About me"
        file: index.qmd
      - projects.qmd
      - blog.qmd
      - icon: github
        href: https://github.com/bradfordjohnson/my-portfolio-v2
format:
  html:
    theme: 
      light: [litera, styles.scss]
      dark: [darkly, styles-dark.scss]
    css: styles.css

editor: visual

