project:
  type: website
output-dir: docs

website:
  title: "Bradford Johnson"
  navbar:
    left: 
      - index.qmd
      - projects.qmd
      - blog.qmd
    right:
      - icon: github
        href: https://github.com/
format:
  html:
    theme: 
      light: [litera, styles.scss]
      dark: [darkly, styles-dark.scss]
    css: styles.css

editor: visual

